const sidebars = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: 'guide', // '.' 即当前 docs 文件夹
    },
  ],
  api: [
    {
      type: 'doc',
      id: 'api',
      label: 'CoNote API'
    }
  ]
};

module.exports = sidebars;
