const sidebars = {
  guide: [
    {
      type: "autogenerated",
      dirName: "guide", // '.' 即当前 docs 文件夹
    },
  ],
  selfHosted: [
    "self-hosted/introduce",
    {
      type: "category",
      label: "Installation",
      items: [
        {
          type: "autogenerated",
          dirName: "self-hosted/installation",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        {
          type: "autogenerated",
          dirName: "self-hosted/configuration",
        },
      ],
    },
    "self-hosted/generate",
  ],
  api: [
    {
      type: "doc",
      id: "api",
      label: "CoNote API",
    },
  ],
};

module.exports = sidebars;
